### ISSUE TITLE
Explore ROS2

### ISSUE THREAD

**Issue by JosephSaliba01** [mcgill-robotics/rover#99]

**Comment by amotaouakkil123** [comment]
Installed ROS2 on my windows system with the demos working properly. Followed this tutorial: https://docs.ros.org/en/iron/Installation/Windows-Install-Binary.html#rqt-dependencies

Now looking into creating a workspace and converting the project. Once that's done I will try the same on Linux and then macOS.

**Comment by amotaouakkil123** [comment]
@mn297 Micro-ROS investigation.

**Comment by amotaouakkil123** [comment]
For any general knowledge on ROS 2: https://www.youtube.com/@RoboticsBackEnd/videos
